<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Theater Movies_w-8 h-8 rounded-full ove_69544b</name>
   <tag></tag>
   <elementGuidId>1019740e-e13f-4d6d-9bed-b93a44e16a03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/header/div/div/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;toppro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>83c1cfa2-676d-4320-a1da-c5603673d284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-8 h-8 rounded-full overflow-hidden cursor-pointer active:scale-90 transition-transform</value>
      <webElementGuid>d4b70fc4-c27f-484b-9d34-7930e37b65f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>toppro</value>
      <webElementGuid>35e093ae-6f44-4560-82e7-0196299f03f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/src/assets/user.png</value>
      <webElementGuid>ff3a163b-b351-4444-b99c-36307ccee838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;pb-14 lg:pb-0&quot;]/header[@class=&quot;fixed top-0 w-full h-16 bg-black opacity-75 z-40&quot;]/div[@class=&quot;container mx-auto px-3 flex items-center h-full&quot;]/div[@class=&quot;ml-auto flex items-center gap-5&quot;]/div[@class=&quot;relative&quot;]/button[@class=&quot;focus:outline-none&quot;]/img[@class=&quot;w-8 h-8 rounded-full overflow-hidden cursor-pointer active:scale-90 transition-transform&quot;]</value>
      <webElementGuid>04be9ef8-d6af-429d-a384-309aa24d989d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/header/div/div/div/button/img</value>
      <webElementGuid>ac3f2687-b609-4b76-867d-abf66b7902ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='toppro']</value>
      <webElementGuid>d47d7e6b-1268-4b46-9fab-8213220bea29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>3bfb95de-741f-44f2-8cb0-778255c76db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'toppro' and @src = '/src/assets/user.png']</value>
      <webElementGuid>49d504a0-5bc4-4dba-9eaa-fb93bd4a75ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
