<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Genre</name>
   <tag></tag>
   <elementGuidId>c6a5d417-8b26-4a7d-932e-e4d7da32d5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > label.flex.items-center.text-sm.font-medium.text-neutral-300.mb-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div/div/div/div/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Genre&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1f5f7c7e-af32-47ca-b7db-4a4702137b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>genre-filter</value>
      <webElementGuid>418a6f4e-0b63-41a7-b178-e56944a1dba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center text-sm font-medium text-neutral-300 mb-1</value>
      <webElementGuid>46e065b8-148c-49e1-8128-58cdd6a71395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Genre</value>
      <webElementGuid>32a0512b-3287-485a-bbb7-ab676fa6a2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;pb-14 lg:pb-0&quot;]/div[1]/div[@class=&quot;py-16&quot;]/div[@class=&quot;container mx-auto&quot;]/div[@class=&quot;mb-8 p-6 bg-neutral-800 rounded-lg shadow-xl&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-3 gap-6&quot;]/div[2]/label[@class=&quot;flex items-center text-sm font-medium text-neutral-300 mb-1&quot;]</value>
      <webElementGuid>65cae1c7-e8ad-42b9-a95c-a24ef4451626</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/div/div/div[2]/label</value>
      <webElementGuid>d4729b12-ec5f-4252-b499-b76547182a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/following::label[1]</value>
      <webElementGuid>53d31225-c99e-418d-83bb-0243ab8fe299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore Movies'])[1]/following::label[2]</value>
      <webElementGuid>ce27d357-3262-4e46-9a1c-eae2efe087f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by Rating'])[1]/preceding::label[1]</value>
      <webElementGuid>e3590a48-8125-4f86-a4f4-7bb7fa2770f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Amateur'])[1]/preceding::label[2]</value>
      <webElementGuid>8d3ea689-5c86-472f-b85b-d293f8b3c0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Genre']/parent::*</value>
      <webElementGuid>25f1eab8-b5d3-4904-800b-94dccd46f332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>94bf03eb-ff3d-4388-aa65-4e50df1b11f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Genre' or . = 'Genre')]</value>
      <webElementGuid>8c3294a0-68dd-4159-8571-49529577121d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
