<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NoneAscendingDescending</name>
   <tag></tag>
   <elementGuidId>81939e6c-2d8e-4443-85bd-0a1ce405dc6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rating-filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='rating-filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sort by Rating&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>725fe445-a010-4731-a37f-d80bb2fb9264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rating-filter</value>
      <webElementGuid>7a5e3026-350f-4058-9852-1e3b7f459c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full p-2.5 bg-neutral-700 border border-neutral-600 text-neutral-200 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500 transition-colors</value>
      <webElementGuid>f0ffb7ca-278e-4430-b989-12dbefc75526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NoneAscendingDescending</value>
      <webElementGuid>d29b7f9b-0c35-448a-aec5-9d9d805719a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rating-filter&quot;)</value>
      <webElementGuid>da76cd1d-63c0-476e-8fb1-ab7943fb6ede</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='rating-filter']</value>
      <webElementGuid>f8fcd190-227c-4347-aa8e-9ba5b670c7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/div/div/div[3]/select</value>
      <webElementGuid>3c46db9a-a63e-4eed-b18a-7d02825129bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by Rating'])[1]/following::select[1]</value>
      <webElementGuid>e8231693-687f-490c-af5d-62719019f4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Genre'])[1]/following::select[2]</value>
      <webElementGuid>46609e39-5d7b-457c-ac07-5c7e6cfd0a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Amateur'])[1]/preceding::select[1]</value>
      <webElementGuid>8013e0ea-2dbe-4724-bb91-a71084759c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Risk'])[1]/preceding::select[1]</value>
      <webElementGuid>1f2aa688-813f-4a7c-a312-8ad84e1ed578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>91ab97b3-a5c6-4610-9d68-68c5392e150f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'rating-filter' and (text() = 'NoneAscendingDescending' or . = 'NoneAscendingDescending')]</value>
      <webElementGuid>638028fe-5e11-466f-a585-e45cfea55461</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
