<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All GenresActionAdultAdventureAnimat_c8c8df</name>
   <tag></tag>
   <elementGuidId>e9c2c1fa-2366-4f70-b9d6-300e04e4842f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#genre-filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='genre-filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Genre&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9b7f05be-6a77-4d98-9694-2d450e7c5e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>genre-filter</value>
      <webElementGuid>913a80e8-2951-4788-b79f-cda4afa01b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full p-2.5 bg-neutral-700 border border-neutral-600 text-neutral-200 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500 transition-colors</value>
      <webElementGuid>503a221d-9e40-4a85-a1dd-d11bbac0ad1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All GenresActionAdultAdventureAnimationBiographyComedyCrimeDocumentaryDramaFamilyFantasyGame-ShowHistoryHorrorMusicMusicalMysteryNewsReality-TVRomanceSci-FiSportTalk-ShowThrillerWarWestern</value>
      <webElementGuid>243a956e-a295-4d2f-b074-26f24d2ff1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;genre-filter&quot;)</value>
      <webElementGuid>edee2956-03a4-45f5-8ab1-ad02a3e55bb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='genre-filter']</value>
      <webElementGuid>1d106a48-005c-4b3b-837d-89ac866efa32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/div/div/div[2]/select</value>
      <webElementGuid>d4c89d72-3836-4877-bd25-9f07a529f8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Genre'])[1]/following::select[1]</value>
      <webElementGuid>d0bf3750-7d68-46d1-b593-b36c563f931e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/following::select[2]</value>
      <webElementGuid>b0cc2860-096c-4efb-b28c-1cac68c01a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by Rating'])[1]/preceding::select[1]</value>
      <webElementGuid>a983ff86-33e7-4b2f-ad94-20046b0391b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Amateur'])[1]/preceding::select[2]</value>
      <webElementGuid>e7212e01-72c8-401e-85bc-a315ab15c825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>8e7c4ac8-e77a-48a3-9c03-7f6542611ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'genre-filter' and (text() = 'All GenresActionAdultAdventureAnimationBiographyComedyCrimeDocumentaryDramaFamilyFantasyGame-ShowHistoryHorrorMusicMusicalMysteryNewsReality-TVRomanceSci-FiSportTalk-ShowThrillerWarWestern' or . = 'All GenresActionAdultAdventureAnimationBiographyComedyCrimeDocumentaryDramaFamilyFantasyGame-ShowHistoryHorrorMusicMusicalMysteryNewsReality-TVRomanceSci-FiSportTalk-ShowThrillerWarWestern')]</value>
      <webElementGuid>e6de59cd-1a9f-4eb1-9bb1-9d04183f7f86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
