<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All Years20252024202320222021</name>
   <tag></tag>
   <elementGuidId>9df7a9ba-97c1-4207-b799-754970c28c13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#year-filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='year-filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Year&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ba54fdba-62fd-4bf7-a8c3-7c1017821df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>year-filter</value>
      <webElementGuid>ed151cd6-7ca5-40fb-8b0c-23959ec87b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full p-2.5 bg-neutral-700 border border-neutral-600 text-neutral-200 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500 transition-colors</value>
      <webElementGuid>9e1feefe-4906-4532-85d9-3dc3037e51d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Years20252024202320222021</value>
      <webElementGuid>ec5255d8-16fd-479e-ad10-28c1621af1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;year-filter&quot;)</value>
      <webElementGuid>029cac63-e7c8-4e2e-8db4-16db411983a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='year-filter']</value>
      <webElementGuid>4055b41f-76a3-4a7a-a7b9-7805f2a4c625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/div/div/div/select</value>
      <webElementGuid>81ec09de-9423-478b-a518-be265de3bf09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/following::select[1]</value>
      <webElementGuid>512b3ec0-9133-4b27-8b7d-dc984585a09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore Movies'])[1]/following::select[1]</value>
      <webElementGuid>3ce8da01-9509-4164-9f1f-5ff49a78b049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Genre'])[1]/preceding::select[1]</value>
      <webElementGuid>fd1998b0-b18a-4c47-acfa-d0bf54f8cbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by Rating'])[1]/preceding::select[2]</value>
      <webElementGuid>74654d92-3638-4d41-a1af-5d71d099d884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2e3fe306-e9be-4971-8b10-a574543570d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'year-filter' and (text() = 'All Years20252024202320222021' or . = 'All Years20252024202320222021')]</value>
      <webElementGuid>e278de88-51cf-4f92-b394-1d1c85f41224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
