
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # volumes:
    #   - mongo_data:/data/db

  mongo-import:
    build: 
      context: .
      dockerfile: Dockerfile.mongo
    container_name: mongo-import
    depends_on:
      - mongo
    command: ["bash", "/scripts/import.sh"]
    restart: "no"

# volumes:
#   mongo_data: 